trainfilePath:
  - /sdf/home/d/dougl215/studies/fakedep/train/
testfilePath:
  - /sdf/home/d/dougl215/studies/fakedep/test/

outdir: /scratch/dougl215/larnd-sim-nd-spatialModel

loss: torchMSE
# batchSize: 512
batchSize: 1024

lr: 1.e-10

nEpochs: 10

layers:

- type: Linear
  out_feat: 32
- type: Linear
  out_feat: 64
- type: Linear
  out_feat: 128
- type: Linear
  out_feat: 64
- type: Linear
  out_feat: 32
- type: Linear
  out_feat: 3
