trainfilePath:
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/edep_single_particle_larndsim_eb5a8574-9c3a-4041-aa5b-590052260d8f.h5
testfilePath:
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/edep_single_particle_larndsim_eb5a8574-9c3a-4041-aa5b-590052260d8f.h5

outdir: /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/singleParticlePNN

batchSize: 32
loss: NLL

nEpochs: 10

layers:

- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 2
