trainfilePath:
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/LE_singleParticle/pared_single_particle_fca09119-24a8-4730-b4f4-4782c4b7add0.h5
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/LE_singleParticle/pared_single_particle_fca09119-24a8-4730-b4f4-4782c4b7add0.h5
testfilePath:
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/LE_singleParticle/pared_single_particle_fca09119-24a8-4730-b4f4-4782c4b7add0.h5

outdir: /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/singleParticle

dataLoader: DataLoader
transform: array_to_sparseTensor
in_feat: 1
batchSize: 10
loss: MSE

nEpochs: 2

layers:

- type: Scaling
  scalingFactor: 0.05
- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 2
 
