trainfilePath:
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/mu_only_train.h5
testfilePath:
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/mu_only_train.h5
  - /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/mu_only_test.h5

outdir: /home/dan/studies/NDLArSimReco/NDLArSimReco/samples/singleParticlePNN_dropout

batchSize: 32
loss: NLL

nEpochs: 10

layers:

- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 2
