trainfilePath:
  - /sdf/group/neutrino/dougl215/singleParticle/batch1k_time_padding_3GeV/shifted/
testfilePath:
  - /sdf/group/neutrino/dougl215/singleParticle/mu_only_3GeV_test/shifted/

outdir: /scratch/dougl215/larndsim_mu_only_PNN_dropout

loss: NLL
batchSize: 128

nEpochs: 10

layers:

- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 2
