trainfilePath:
  - /sdf/group/neutrino/dougl215/singleParticle/singleParticle_3GeV/pared_shifted
testfilePath:
  - /sdf/group/neutrino/dougl215/singleParticle/singleParticle_3GeV_test/pared_shifted

outdir: /scratch/dougl215/larndsim_mu_only_PNN_dropout

loss: NLL
batchSize: 64

nEpochs: 20
lr: 1.e-4

layers:

- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 128
- type: MReLU
- type: MDropout
- type: MConvolution
  kernel_size: 5
  stride: 1
  out_feat: 2
