trainfilePath: 
  - /sdf/group/neutrino/dougl215/singleParticle/batch1k_time_padding_3GeV/mu-only-3GeV-joined.h5
testfilePath: 
  - /sdf/group/neutrino/dougl215/singleParticle/batch1k_time_padding_3GeV/mu-only-3GeV-joined.h5
outdir: /scratch/dougl215/larndsim_mu_only

batchSize: 64

nEpochs: 10

layers:

- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 1
