trainfile: /sdf/group/neutrino/dougl215/singleParticle/batch1k/larndsim_output/edep_single_particle_larndsim_f5741683-6872-49e5-983d-c4881b6af3e7.h5
testfile: /sdf/group/neutrino/dougl215/singleParticle/batch1k/larndsim_output/edep_single_particle_larndsim_f5966a8e-3b49-4801-b6d6-84f9b211aa69.h5
outdir: /scratch/dougl215/larndsim_mlp

nEpochs: 1

layers:

- type: MLinear
  out_feat: 256
- type: MLinear
  out_feat: 256
- type: MLinear
  out_feat: 5