trainfilePath: 
  - /sdf/group/neutrino/dougl215/singleParticle/mu_only_3GeV/shifted/
testfilePath: 
  - /sdf/group/neutrino/dougl215/singleParticle/batch1k_time_padding_3GeV/shifted/
outdir: /scratch/dougl215/larndsim_mu_only

loss: MSE
batchSize: 64

nEpochs: 10

layers:

- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 128
- type: MReLU
- type: MConvolution
  kernel_size: 7
  stride: 1
  out_feat: 1
