trainfile: /sdf/group/neutrino/dougl215/singleParticle/batch1k_time_padding_3GeV/larndsim_output/edep_single_particle_larndsim_fbee8d4c-7776-4816-91ce-fe626ec7fd3d.root
testfile: /sdf/group/neutrino/dougl215/singleParticle/batch1k_time_padding_3GeV/larndsim_output/edep_single_particle_larndsim_fbee8d4c-7776-4816-91ce-fe626ec7fd3d.root
outdir: /scratch/dougl215/larndsim_mlp

nEpochs: 1

layers:

- type: MLinear
  out_feat: 256
- type: MLinear
  out_feat: 256
- type: MLinear
  out_feat: 5